package br.com.matheus.agendamentoconsultas.model.enums;

public enum Especializacao {

	IMUNOLOGIA,
	ANESTESIOLOGIA,
	ANGIOLOGIA,
	CARDIOLOGIA,
	CLINICA,
	COLOPROCTOLOGIA,
	DERMATOLOGIA,
	ENDOCRINOLOGIA,
	GASTROENTEROLOGIA,
	GENETICA_MEDICA,
	GERIATRIA,
	GINECOLOGIA,
	HEMATOLOGIA,
	INFECTOLOGIA,
	MASTOLOGIA,
	ESPORTIVA,
	PERICIA,
	NEFROLOGIA,
	NEUROLOGIA,
	OFTALMOLOGIA,
	ONCOLOGIA,
	ORTOPEDIA,
	OTORRINOLARINGOLOGIA,
	PATOLOGIA,
	PEDIATRIA,
	PNEUMOLOGIA,
	PSIQUIATRIA,
	REUMATOLOGIA,
	UROLOGIA
}